spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.92.109:3306/cy_database?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5
      filters: com.cypher.databaseconnection.ConnectionLogFilter, stat, slf4j, wall
